#!/bin/bash

DIR="$( dirname $( realpath "$0" ) )"
 
&>/dev/null pushd "$DIR"

function silentpop {
  &>/dev/null popd
}

trap silentpop EXIT

[[ -f ".build/release/ocr" ]] || swift build -c release

.build/release/ocr "$@"

